---
- name: Update pianopi
  hosts: pianopi
  become: yes
  tasks:
    - name: Ensure packages are up to date
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
